[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"  

